### ISSUE TITLE
A load of sparrows in the plants!

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#141]
This plant genus seems to contain a large number of sparrow species!
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree3.0@25031/Sorella](https://tree.opentreeoflife.org/opentree/opentree3.0@25031/Sorella) |
| Target node label | Sorella |
| Synthetic tree id | opentree3.0 |
| Synthetic tree node id | 25031 |
| Source tree id(s) | silva:AF488406/#6,ncbi:66381,gbif:2492321,irmng:1280381 |
| Open Tree Taxonomy id | 734179 |
| Intended scope | Re: synthetic tree |

**Comment by hyanwong** [comment]
Sorry - 'red algae' genus (plants sensu lato). Principle is the same either way - sparrows shouldn't be here

# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |

**Comment by jar398** [comment]
OTT 2.8 was confused; I don't know how all those Passers ended up there. The problem seems to be fixed in 2.9. I see only the following species in that genus in OTT 2.9. Because of their presence in WoRMS I'm assuming they're all rhodophytes.

429199  |   734179  |   Sorella delicatula  |   species |   ncbi:48481,worms:372806,gbif:5278261,irmng:10017784 |       |       |  
1014547 |   734179  |   Sorella repens  |   species |   ncbi:189632,worms:372445,gbif:5278260,irmng:11164030    |       |       |  
4011235 |   734179  |   Sorella pinnata |   species |   worms:372807,gbif:5278265,irmng:10017785    |       |       |  
4011236 |   734179  |   Sorella pulchra |   species |   worms:372444,gbif:5278264,irmng:11224439    |       |       |

**Comment by jar398** [comment]
When a name makes a really big move in the taxonomy (e.g. rhotodphytes to animals), it generally gets a new OTT id.  Sorry.  There is a last-ditch TNRS lookup before synthesis, which would probably catch these, at least for synthetic tree construction. Other applications will just have to do the lookup again.

**Comment by hyanwong** [comment]
Great that it's corrected in OTT 2.9. Does that mean that when 2.9 is released (imminently, I presume), then the TNRS will return the new IDs, and will return these passerines for context_name = "Vertebrates", even if draft version 4 of the tree hasn't been released? Or do both a new tree and a new taxonomy get released simultaneously?

Also, I can see that big moves like this result in a new OTTid, but have about small moves e.g. from one genus to another within the same family? How likely is it that these taxa will have changed numbers?

**Comment by jar398** [comment]
It looks like the new taxonomy / TNRS and synthetic tree will all be moved
to production at the same time. If you want to see what these may look like
(if we don't revise them again) visit devtree.opentreeoflife.org and try
the api interface at devapi.opentreeoflife.org.

The OTT id will change on a 'move' like this, roughly speaking, if and only
if a name moves from one 'barrier' taxon to a disjoint (i.e.
non-ancestor/descendant) barrier taxon.  The barrier taxa are listed here:
https://github.com/OpenTreeOfLife/reference-taxonomy/blob/master/tax/skel/taxonomy.tsv

You can also see an id change in other circumstances, such as 'lumping'
(discovery that two names, or ids, refer to a single taxon rather than two
taxa). In the 2.9 taxonomy release there is a forwards.tsv file that tells
you how to replace old ids with new ids in this situation.

**Comment by hyanwong** [comment]
On 27 Oct 2015, at 13:19, Jonathan A Rees notifications@github.com wrote:

> The OTT id will change on a 'move' like this, roughly speaking, if and only
> if a name moves from one 'barrier' taxon to a disjoint (i.e.
> non-ancestor/descendant) barrier taxon. The barrier taxa are listed here:
> https://github.com/OpenTreeOfLife/reference-taxonomy/blob/master/tax/skel/taxonomy.tsv

Thanks, that�s really helpful.
