### ISSUE TITLE
Strange synonymy

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#146]
Strangely (to me) this species crops up as a synonym when searching for "Delphinus capensis" in the search box or via the march_names API. Why is this?
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree3.0@771184/Cephalorhynchus-heavisidii](https://tree.opentreeoflife.org/opentree/opentree3.0@771184/Cephalorhynchus-heavisidii) |
| Target node label | Cephalorhynchus heavisidii |
| Synthetic tree id | opentree3.0 |
| Synthetic tree node id | 771184 |
| Source tree id(s) | ncbi:103583,gbif:5220041,irmng:11241419 |
| Open Tree Taxonomy id | 860906 |
| Intended scope | Re: OTT taxon |

**Comment by jar398** [comment]
OTT 2.8 synonymizes these two due to
http://www.marinespecies.org/aphia.php?p=taxdetails&id=383815 (which it got
indirectly through IRMNG).  The two seem to be distinct in OTT 2.9 (even
though 2.9 uses the same IRMNG dump). I think we can credit a synonym
suppression rule suggested by Mark Holder and newly implemented in OTT 2.9.

**Comment by jar398** [comment]
Often you can answer 'why is the taxonomy like this' questions yourself by querying each of the taxonomy sources listed in the source ids list for the taxon name. Maybe that's more time consuming than what I do, which is to search in the canonicalized copies that I have, but it works either way.

**Comment by hyanwong** [comment]
Now working as expected (OTT 2.9)
