### ISSUE TITLE
Various passerines missing from the devtree

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#147]
When querying the API via http://devapi.opentreeoflife.org/v2/tnrs/match_names, the following names no longer match (they do using the non-development API). This is also reflected when searching using the search box in the devtree vs the stable tree. Even if these taxa have been lumped or otherwise changed, they should appear as synonyms, in the devtree, no? Anyway, AFAIK these haven't changed taxonomic status, and include some fairly well-known species which anyone would expect to find in the OpenTree (e.g. the goldcrest,Regulus regulus.

['Compsospiza baeri', 'Regulus satrapa', 'Hyliota usambara']
['Regulus regulus', 'Hyliota violacea', 'Hyliota australis']
['Chamaea fasciata', 'Neomixis flavoviridis', 'Regulus calendula', 'Regulus madeirensis']
['Regulus goodfellowi', 'Cryptosylvicola randrianasoloi', 'Hyliota flavigaster']
['Amaurocichla bocagei', 'Thamnornis chloropetoides']
['Regulus ignicapilla', 'Panurus biarmicus']

**Comment by jar398** [comment]
This is related to
https://github.com/OpenTreeOfLife/reference-taxonomy/issues/153; see the
discussion there and visit
http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Undef&id=552884&lvl=3&lin=f&keep=1&srchmode=1&unlock
noting the 'unclassified' in the lineage.

But they should be offered by the TNRS regardless of their 'unclassified'
status, since 'unclassified' is just another name for 'incertae sedis'.
OTTFlag.java should be fixed; I'll file an issue.

tax/ott/taxonomy.tsv:3599325 | 3599326 | Regulus satrapa | species |
ncbi:13245,gbif:2484591,irmng:11269850 | | unclassified_inherited |

Also related to
https://github.com/OpenTreeOfLife/reference-taxonomy/issues/173 .

**Comment by mtholder** [comment]
Yes. this is disappointing. There was some discussion of this: https://github.com/OpenTreeOfLife/reference-taxonomy/issues/153
I know that we have talked about not pruning the incertae sedis taxa from the supertree. I can't remember what the timeline for that is.

**Comment by hyanwong** [comment]
On 28 Oct 2015, at 14:56, Jonathan A Rees notifications@github.com wrote:

> But they should be offered by the TNRS regardless of their 'unclassified'
> status, since 'unclassified' is just another name for 'incertae sedis'.
> OTTFlag.java should be fixed; I'll file an issue.

Yes, for my use case, all I want to do is to obtain an OTT ID for these taxa. So I guess once your fix has gone in, I can do this via the API, even if they are �unclassified�? And I presume that their ott ID won�t change in 2.10 either. Or will it?

**Comment by jar398** [comment]
They should be available via the API, yes. And I work very hard to keep ids
stable. (but I don't always succeed.) I do this by manually reviewing the
deprecated.tsv file on every taxonomy build.

Ordinarily ids aren't stable until a taxonomy version is 'released'. That
is, some X could have different ids in 2.XdraftY and in 2.Xdraft(Y+1).
Fixing Choanoflagellida in a later 2.9 draft is incompatible with treating
2.9draft12 ids as stable. We get stability when we decide that there will
be no more drafts of a version. I _think_ we've decided this about
2.9draft12, but if you lobbied for another draft there might still be a
chance to make one. A decision on that is due Monday, and you can lobby if
you like.

The reason this is important is because in the past we've had really long
intervals between taxonomy releases. I expect the pace will pick up, but
I'm warning that it could be a while before there's a 2.10 (and a
Choanoflagellida fix).

**Comment by hyanwong** [comment]
Closed assuming 'Should be available later tonight': https://github.com/OpenTreeOfLife/taxomachine/issues/108

**Comment by jar398** [comment]
I see Regulus regulus in TNRS results now

**Comment by hyanwong** [comment]
Yes, although contexts are borked, e.g. 

curl -X POST http://devapi.opentreeoflife.org/v2/tnrs/match_names -H "content-type:application/json" -d '{"names": ["Hylobates"], "context_name": "Mammals"}' 

gives nothing, but this gibbon search is OK:

curl -X POST http://devapi.opentreeoflife.org/v2/tnrs/match_names -H "content-type:application/json" -d '{"names": ["Hylobates"]}'

**Comment by josephwb** [comment]
@hyanwong a new DB has been deployed on dev. the contexts had not been built. your mammal query works:

```
josephwb@wopr:~/Work/OToL/taxomachine$ curl -X POST http://devapi.opentreeoflife.org/v2/tnrs/match_names -H "content-type:application/json" -d '{"names": ["Hylobates"], "context_name": "Mammals"}'
{
  "governing_code" : "ICZN",
  "unambiguous_name_ids" : [ "Hylobates" ],
  "unmatched_name_ids" : [ ],
  "matched_name_ids" : [ "Hylobates" ],
  "context" : "Mammals",
  "includes_deprecated_taxa" : false,
  "includes_dubious_names" : false,
  "includes_approximate_matches" : true,
  "taxonomy" : {
    "weburl" : "https://github.com/OpenTreeOfLife/opentree/wiki/Open-Tree-Taxonomy",
    "author" : "open tree of life project",
    "source" : "ott2.9draft12"
  },
  "results" : [ {
    "id" : "Hylobates",
    "matches" : [ {
      "matched_node_id" : 2604776,
      "synonyms" : [ "Cheiron", "Laratus", "Hylobatus", "Brachitanytes", "Hilobates", "Gibbon", "Hylobates" ],
      "flags" : [ ],
      "ot:ottTaxonName" : "Hylobates",
      "search_string" : "hylobates",
      "matched_name" : "Hylobates",
      "is_synonym" : false,
      "score" : 1.0,
      "unique_name" : "Hylobates (genus in Deuterostomia)",
      "ot:ottId" : 166552,
      "is_deprecated" : false,
      "nomenclature_code" : "ICZN",
      "is_approximate_match" : false,
      "rank" : "",
      "is_dubious" : false
    } ]
  } ]
}
```

**Comment by hyanwong** [comment]
Yes, this now all woks as expects. Thanks. Can we close this issue, then?
