### ISSUE TITLE
This family should only contain a single extant species (Sphenodon punctatus)

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#165]
All other descendants of this node should be marked extinct.
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/opentree4.0@1447928/Sphenodontidae](https://tree.opentreeoflife.org/opentree/argus/opentree4.0@1447928/Sphenodontidae) |
| Target node label | Sphenodontidae |
| Synthetic tree id | opentree4.0 |
| Synthetic tree node id | 1447928 |
| Source tree id(s) | ncbi:8506,gbif:5684,irmng:104181 |
| Open Tree Taxonomy id | 35887 |
| Intended scope | Re: OTT taxon |

**Comment by jar398** [comment]
See https://github.com/OpenTreeOfLife/reference-taxonomy/issues/176

**Comment by jar398** [comment]
Fixing the heuristic didn't help; the taxa are marked neither fossil nor extant in IRMNG.
I'll make an ad hoc patch.

**Comment by jar398** [comment]
Wikipedia: "The tuatara Sphenodon punctatus has been protected by law since 1895.[11][12] A second species, S. guntheri, was recognised in 1989[6] but since 2009 its use has been discontinued.[13][page needed]"

CoL concurs: http://www.catalogueoflife.org/col/search/all/key/Sphenodon+guntheri/fossil/0/match/1

So I need to make guntheri a synonym for punctatus (thereby merging the two NCBI taxa), and send a correction to NCBI.

**Comment by mtholder** [comment]
fixed in previous OTT
