### ISSUE TITLE
Where are all the microsporidia?

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#176]
There should be over 1000 species in here, e.g. http://www.ncbi.nlm.nih.gov/pmc/articles/PMC130667/ quotes 1200 spp.
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/ottol@16113/Microsporidia](https://tree.opentreeoflife.org/opentree/argus/ottol@16113/Microsporidia) |
| Target node label | Microsporidia |
| Synthetic tree id | opentree4.0 |
| Synthetic tree node id | 879312 |
| Source tree id(s) | h2007:10,if:99056,ncbi:6029,worms:391932,irmng:174 |
| Open Tree Taxonomy id | 16113 |
| Intended scope | Re: synthetic tree |

**Comment by hyanwong** [comment]
As a followup, here is a tree with 6 microsporidian genomes: http://www.biomedcentral.com/1741-7007/10/47

**Comment by jar398** [comment]
The NCBI fungi-only taxa were suppressed at the request of our fungi
experts, who considered IF authoritative for fungi, so that may be some of
the problem. NCBI Microsporidia had many casualties, which is unfortunate
because IF's coverage of Microsporidia didn't seem good to me. (And the
version we obtained didn't even consider them to be fungi.)

Every source taxonomy classifies this phylum(?) in a radically different
way. Below are some links in case you want to compare the taxonomies. Looks
like we probably have some bogus homonyms (same genus from two taxonomies
appearing in two places because of a barrier between the locations); maybe
there is disagreement over what is and isn't a microsporidian in the first
place.

I think this requires review, and someone should make a recommendation for
what to do. We could take either WoRMS or NCBI as higher priority than IF,
get a new taxonomic source, etc.

phylum Microsporidia
http://varela.csail.mit.edu/cgi-bin/browse?16113 h2007:10, if:99056
http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=99056,
ncbi:6029 http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=6029,
worms:391932 http://www.marinespecies.org/aphia.php?p=taxdetails&id=391932,
irmng:174 http://www.marine.csiro.au/mirrorsearch/ir_search.taxon_info?id=174
  a.k.a. microsporidians
  Fungi http://varela.csail.mit.edu/cgi-bin/browse?352914 <
Nucletmycea http://varela.csail.mit.edu/cgi-bin/browse?5246132 <
Opisthokonta http://varela.csail.mit.edu/cgi-bin/browse?332573 <
Eukaryota http://varela.csail.mit.edu/cgi-bin/browse?304358 <
cellular organisms http://varela.csail.mit.edu/cgi-bin/browse?93302
< life http://varela.csail.mit.edu/cgi-bin/browse?805080
class Marinosporidia
http://varela.csail.mit.edu/cgi-bin/browse?5584463 worms:564923
http://www.marinespecies.org/aphia.php?p=taxdetails&id=564923,
irmng:1557 http://www.marine.csiro.au/mirrorsearch/ir_search.taxon_info?id=1557
- genus Zelenkaia http://varela.csail.mit.edu/cgi-bin/browse?5584442
  if:581558 http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=581558
  major_rank_conflict, hidden, unplaced
- genus Cocconema (genus in phylum Opisthokonta)
  http://varela.csail.mit.edu/cgi-bin/browse?5584443 if:30087
  http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=30087
  major_rank_conflict, hidden, unplaced
- genus Mariona http://varela.csail.mit.edu/cgi-bin/browse?5584440
  if:30518 http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=30518
  major_rank_conflict, hidden, unplaced
- genus Sarcocystis (genus in phylum Opisthokonta)
  http://varela.csail.mit.edu/cgi-bin/browse?5584441 if:584190
  http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=584190
  major_rank_conflict, hidden, unplaced
- class Rudimicrosporea
  http://varela.csail.mit.edu/cgi-bin/browse?5584446 if:90611
  http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=90611,
  irmng:1330 http://www.marine.csiro.au/mirrorsearch/ir_search.taxon_info?id=1330
  hidden
- genus Cucumispora
  http://varela.csail.mit.edu/cgi-bin/browse?5584447 ncbi:1649875
  http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=1649875,
  worms:819435 http://www.marinespecies.org/aphia.php?p=taxdetails&id=819435
  sibling_higher, incertae_sedis, hidden
- class Microsporea (inconsistent in Microsporidia)
  http://varela.csail.mit.edu/cgi-bin/browse?5584444 if:99022
  http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=99022,
  worms:391980 http://www.marinespecies.org/aphia.php?p=taxdetails&id=391980,
  gbif:285 http://www.gbif.org/species/285/, irmng:1312
  http://www.marine.csiro.au/mirrorsearch/ir_search.taxon_info?id=1312
  barren, hidden, inconsistent
- genus Tylogonus (genus in Nucletmycea)
  http://varela.csail.mit.edu/cgi-bin/browse?5584445 if:548157
  http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=548157
  major_rank_conflict, hidden
- genus Mesnilia (genus in Nucletmycea)
  http://varela.csail.mit.edu/cgi-bin/browse?5584438 if:584031
  http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=584031
  major_rank_conflict, hidden, unplaced
- genus Spirillonema
  http://varela.csail.mit.edu/cgi-bin/browse?5584439 if:584191
  http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=584191
  major_rank_conflict, hidden, unplaced
- species Microsporidia sp. NIK-55Dp
  http://varela.csail.mit.edu/cgi-bin/browse?5584458 ncbi:1631734
  http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=1631734
  unclassified, sibling_higher
- order Microsporea incertae sedis
  http://varela.csail.mit.edu/cgi-bin/browse?5584459 worms:565137
  http://www.marinespecies.org/aphia.php?p=taxdetails&id=565137
  barren, sibling_higher, was_container, incertae_sedis, unplaced
- species Microsporidia sp. EC-1
  http://varela.csail.mit.edu/cgi-bin/browse?5584456 ncbi:1718677
  http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=1718677
  unclassified, sibling_higher
- species Microsporidia sp. VIK-52Pr
  http://varela.csail.mit.edu/cgi-bin/browse?5584457 ncbi:1631740
  http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=1631740
  unclassified, sibling_higher
- family Areosporiidae
  http://varela.csail.mit.edu/cgi-bin/browse?5584462 worms:819412
  http://www.marinespecies.org/aphia.php?p=taxdetails&id=819412
  sibling_higher, incertae_sedis, unplaced
- order Minisporida
  http://varela.csail.mit.edu/cgi-bin/browse?5584460 worms:564945
  http://www.marinespecies.org/aphia.php?p=taxdetails&id=564945,
  irmng:10862 http://www.marine.csiro.au/mirrorsearch/ir_search.taxon_info?id=10862
  barren, sibling_higher
- order Meiodihaplophasida
  http://varela.csail.mit.edu/cgi-bin/browse?5584461 worms:819390
  http://www.marinespecies.org/aphia.php?p=taxdetails&id=819390
  barren, sibling_higher
- species Microsporidia sp. NIK-61Pp
  http://varela.csail.mit.edu/cgi-bin/browse?5584450 ncbi:1631737
  http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=1631737
  unclassified, sibling_higher
- species Microsporidia sp. NIK-57Sl
  http://varela.csail.mit.edu/cgi-bin/browse?5584451 ncbi:1631735
  http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=1631735
  unclassified, sibling_higher
- genus Mitosporidium
  http://varela.csail.mit.edu/cgi-bin/browse?5584448 ncbi:1633384
  http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=1633384
  sibling_higher, incertae_sedis, hidden
  ... 43 more children

**Comment by hyanwong** [comment]
Can we ping this to a fungal expert? Wasn't there a student specifically interested in fungal phylogenies? I also notice that some other basal 'fungi' in the same superphylum Opisthosporidia  (esp the Aphelida: Aphelidium, Amoeboaphelidium, & Pseudaphelidium) are missing. There's a recent paper at http://www.ncbi.nlm.nih.gov/pubmed/24734027 and some of their names are present in OTT but missing from the synth tree. Others are missing even from OTT. Again, one for the fungal experts to sort out, I hope.

**Comment by hyanwong** [comment]
FWIW, there was a semi-reasonable microsporidian subtree present in the synthetic tree, draft version 3. Although it contained a lot of Microsporidium_sp_RANDOM_LETTER_CODES.

**Comment by hyanwong** [comment]
These are back again in 11.4 and 12.3
