### ISSUE TITLE
Raphus ineptus is a synonym for Raphus cucullatus

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#187]
No longer inept (!)
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree4.0@1415082/Raphus-ineptus](https://tree.opentreeoflife.org/opentree/opentree4.0@1415082/Raphus-ineptus) |
| Target node label | Raphus ineptus |
| Synthetic tree id | opentree4.0 |
| Synthetic tree node id | 1415082 |
| Source tree id(s) | irmng:11452078 |
| Open Tree Taxonomy id | 3596701 |
| Intended scope | Re: OTT taxon |

**Comment by hyanwong** [comment]
Normally I'd not give wikipedia as a source, but dodos are so well covered that it's an obvious one: https://en.wikipedia.org/wiki/Dodo

**Comment by jar398** [comment]
We have about 500,000 taxa coming from IRMNG only, and on balance I think we shouldn't be including them. (We can still get extinct annotation from IRMNG, and provide linkouts, I'm just suggesting not including taxa like this that do not also come from GBIF, NCBI, etc.)

**Comment by hyanwong** [comment]
Possibly worth sampling from the 500,000 at random, just to see what proportion are bad.

**Comment by Katzlab** [comment]
define bad?

**Comment by hyanwong** [comment]
Indeed. It is obvious in this case (name is an obsolete synonym). I'm assuming that others may be of this ilk, but it they will need careful checking by hand. Perhaps @jar398 could throw 20 or so randomly chosen into this thread, and I can have a look to see what they might represent?

**Comment by jar398** [comment]
I'll take you up on that! The following is not a completely random sample, but I think it will do.

I did already check that none of these 500,000 is mentioned in any OTU mapping in the phylesystem. I also inspected all of the families that we'd lose to make sure we'd be happy losing them (we will be).

```
4717127 |   4717121 |   Schmidtilites   |   genus   |   irmng:1068986   |       |   extinct,extinct_inherited,barren    |   
5811294 |   3316746 |   Epanusia bifasciatus    |   species |   irmng:10230118  |       |       |   
5035961 |   331969  |   Hexatoma retrograda |   species |   irmng:11177954  |       |       |   
5832561 |   5542519 |   Phytoecia hispanica |   species |   irmng:10975405  |       |       |   
3389115 |   968359  |   Ixais   |   genus   |   irmng:1209079   |       |   sibling_higher,barren   |   
5045061 |   907895  |   Zeugophora himalayana   |   species |   irmng:11664292  |       |       |   
4634713 |   91356   |   Nobius tessmanni    |   species |   irmng:10428477  |       |       |   
3136393 |   729305  |   Catasticta microperuviana   |   species |   irmng:11309001  |       |       |   
3110417 |   731213  |   Phalanta exulans    |   species |   irmng:10982343  |       |       |   
3159541 |   3154060 |   Ancylosis macedonica    |   species |   irmng:11311785  |       |       |   
4246353 |   1030857 |   Orthosia juncta |   species |   irmng:10473125  |       |       |   
4262531 |   4262374 |   Adonisea pyraloides |   species |   irmng:11269791  |       |       |   
5334899 |   965954  |   Xanthocera  |   genus   |   irmng:1368514   |   Xanthocera (genus in superorder Amphiesmenoptera)   |   major_rank_conflict,barren  |   
4188489 |   1095594 |   Tristanacris    |   genus   |   irmng:1169181   |       |   major_rank_conflict,barren  |   
4221898 |   603650  |   Faliscomiris    |   genus   |   irmng:1214217   |       |   major_rank_conflict,barren  |   
4676388 |   1002727 |   Aetidius    |   genus   |   irmng:1419444   |       |   barren  |   
5112290 |   3536193 |   Calacarus microrostrus  |   species |   irmng:11651359  |       |       |   
5097405 |   14825   |   Conomma troglodytes |   species |   irmng:11529005  |       |       |   
3544856 |   530043  |   Sitticus nitidus    |   species |   irmng:10539419  |       |       |   
2845577 |   310347  |   Diporochaeta cygnus |   species |   irmng:10009380  |       |       |   
4166605 |   251556  |   Pisciola    |   genus   |   irmng:1439546   |       |   sibling_higher,barren   |   
5427893 |   322246  |   Pyxidicula praetexta    |   species |   irmng:11803040  |       |   hidden  |   
5357034 |   5353651 |   Daphnidium boreale  |   species |   irmng:11806535  |       |   hidden  |   
```

**Comment by jar398** [comment]
Maybe I spoke too soon... my script for checking for study OTUs from IRMNG
had a flaw, and it turns out we're using 171 IRMNG-only taxa as OTUs.  We
can make special cases of these, of course, but it does suggest we're
getting significant mileage out of IRMNG.

Here is a sample of those taxa, with the study ids indicated. If you'd
check these for sanity (are they synonyms, bad names, equivalent to other
names in OTT, etc.) I'd appreciate it. Oh yes Homo habilis is also in the
list, is that a current name?

```
5048849 | 142445 | Dicordylus binotatus | species | irmng:11612940 | | |
```

ot_629
    5048904 | 4606635 | Parallocorynus bicolor | species | irmng:11613985 |
| | ot_626,ot_630
    5048892 | 3407760 | Homalocerus plaumanni | species | irmng:11522352 | |
| ot_636
    5048896 | 3407760 | Homalocerus acuminatus | species | irmng:11522349 |
| | ot_636
    3125467 | 961886 | Eurybia franciscana | species | irmng:11198987 | | |
ot_524
    3194324 | 718172 | Alypia edwardsii | species | irmng:10330201 | | |
pg_1413
    3438979 | 1082612 | Austrogoniodes bicornutus | species | irmng:10060709
| | | pg_2087
    2974687 | 916271 | Albunea occulatus | species | irmng:10530648 | | |
pg_1252
    3624238 | 701516 | Hypsidoridae | family | irmng:102843 | |
sibling_higher,extinct,barren | ot_625,ot_595
    3600779 | 1065611 | Trogon aurantiventris | species | irmng:10522666 | |
| ot_147
    3600208 | 210494 | Piculus leucolalemus | species | irmng:10525002 | | |
ot_158
    5857210 | 521835 | Eupodotis afraoides | species | irmng:10801449 | | |
ot_521
    5560100 | 73554 | Hylexetastes brigidai | species | irmng:10217580 | | |
ot_409
    3607521 | 663303 | Megaladapis grandidieri | species | irmng:11078603 |
| extinct,extinct_inherited | ot_722
    3615030 | 3614882 | Mesohippus bairdi | species | irmng:10692824 | |
extinct,extinct_inherited | pg_2647
    698994 | 626551 | Pouteria brownlessiana | species | irmng:10248117 | |
| pg_227,pg_188
    467131 | 626551 | Pouteria sebertii | species | irmng:10607007 | | |
pg_227,pg_1018,pg_792,ot_409,pg_188
    366612 | 626551 | Pouteria vieillardii | species | irmng:10243075 | | |
pg_227,pg_1018,pg_792,ot_409,pg_188
    171 lines

**Comment by jar398** [comment]
Please continue the IRMNG discussion here: https://github.com/OpenTreeOfLife/reference-taxonomy/issues/211

**Comment by jar398** [comment]
I think the particular case is fixed, but I'm going to leave the issue open to let the conversation run its source.

@Katzlab I think when I say "bad" I mean not accepted; there is a different name out there that's better accepted (by the 'taxonomic community'), or else it's impossible to figure out what the name means, as often happens when the name is old. IRMNG annotates its records with 'nomen nudum' and things like that.  Here's a partial list...
- 'novum'
- 'unavailable'
- 'nudum'
- 'invalid'
- 'dubium'
- 'rejiciendum'
- 'unavailable (except homonymy)'
- 'rejiciandum'
- 'nom. rev.'
- 'nom. conf.'
- 'dubimum'
- 'invalidum'
- 'superfluum'
- 'unjustified emendation'
- 'nom. rej.'
- 'illegitimate'
- 'nom. illeg.'
- 'anticipatione'
- 'misspelling / subsequent emendation'
- 'Nom. rej.'
- 'oblitum'
- 'illegitimum'
- 'nom. rej. prop.'
- 'rejected name (non binomial work)'

**Comment by jar398** [comment]
The name Raphus ineptus is gone from OTT 2.10. (but it may return later, as I keep changing my mind on how to treat IRMNG.)
In any case, closing the issue.
