### ISSUE TITLE
"Actinopterygii" is wrongly equated with "Osteichthyes" in OTT

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#194]
curl -X POST https://api.opentreeoflife.org/v2/tnrs/match_names -H "content-type:application/json" -d '{"names":["Actinopterygii","Osteichthyes"]}'

These are not the same, since Osteichthyes includes lobe fins. If anything, Osteichthyes should be synonymized with Euteleostomi (ott 114654)

**Comment by mtholder** [comment]
thanks. https://tree.opentreeoflife.org/taxonomy/browse?name=Osteichthyes
and examination of the taxonomy files reveals that this is an issue with the taxonomy (rather than just the match_names API call).
It seems a bit hard to diagnose because we don't seem to store source info for the synonym statements (I'll create an issue for that).

**Comment by jar398** [comment]
The culprit is WoRMS.

tax/worms/synonyms.tsv:10194 | Osteichthyes | synonym | |

http://www.marinespecies.org/aphia.php?p=taxdetails&id=152352

which says:

_source of synonymy_ Eschmeyer, W. N. (ed). Catalog of Fishes: Genera,
Species, References., _available online at_
http://researcharchive.calacademy.org/research/Ichthyology/catalog/fishcatmain.asp

I poked around at the calacademy site a bit and couldn't figure out how it
is a source of this synonymy.

This will have to be patched. And yes synonym source support has to be
added to OTT.

**Comment by pmidford** [comment]
Agree - CoF doesn't have much above the family level - we had to fill a
lot of that in when starting the taxonomy for Phenoscape.  The WoRMS
reference is pretty old too.

**Comment by hyanwong** [comment]
On 4 Feb 2016, at 02:39, Jonathan A Rees notifications@github.com wrote:

> I poked around at the calacademy site a bit and couldn't figure out how it
> is a source of this synonymy.

The most recent high-profile use of Osteichthyes as a monophyletic group including lobe fins and ray fins (i.e. equivalent to Euteleostomi) is the DeepFin tree: 

http://currents.plos.org/treeoflife/article/the-tree-of-life-and-a-new-classification-of-bony-fishes/

**Comment by jar398** [comment]
Synonym source and type support is in smasher and will be reflected in OTT 2.10.

So at the very least I should remove the WoRMS synonym.

To recap: DeepFin says Osteichthyes = Actinopterygii + Sarcopterygii. NCBI calls it Euteleostomi. This is a pretty easy fix.

WoRMS says the synonym is 'unaccepted'. I wonder if we should be filtering out unaccepted WoRMS synonyms...
