### ISSUE TITLE
Elephant taxonomic errors

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#221]
# Elephas bombifrons should be Stegodon bombifrons, not in the family Elephantidae but in the family Stegodontidae.  No one uses the subspecies nomen 'knochenhaueri" for Loxodonta africana and there are no acknowledged subspecies for this species.  There is no Elephas primigenius, rather there is Mammuthus primigenius (woolly mammoth)
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [William Sanders](mailto:wsanders@umich.edu) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/ottol@541924/Elephantidae](https://tree.opentreeoflife.org/opentree/argus/ottol@541924/Elephantidae) |
| Target node label | Elephantidae |
| Synthetic tree id | opentree4.0 |
| Synthetic tree node id | 1375683 |
| Source tree id(s) | ncbi:9780,gbif:9427,irmng:105769 |
| Open Tree Taxonomy id | 541924 |
| Intended scope |  |

**Comment by jar398** [comment]
Do you know of a publication that documents a treatment of this group that
you think is correct?

**Comment by jar398** [comment]
I emailed Dr. Sanders who replied: "most of the vital events in proboscidean evolution occurred in Afro-Arabia, so this chapter from the Werdelin and Sanders book (Cenozoic Mammals of Africa, 2010, University of California Press, Berkeley) will be very relevant.  Some changes and additions have occurred since that publication, but this is fundamentally solid in terms of taxonomy and relationships.  The Shoshani and Tassy book "Proboscidea" from 1996 is also a useful volume, and Shoshani and Tassy have published a number of proboscidean systematic and taxonomic papers together since then, as well."

**Comment by mtholder** [comment]
S. bombifrons will be fixed with https://github.com/OpenTreeOfLife/edOTTs/commit/e600e7c2a60b2111f150db61fe732d54c98e45f8  *Mammuthus primigenius* issue already fixed in a previous OTT update, and the *knochenhaueri* subspecies issue is going to stick with us until NCBI fixes it.
