### ISSUE TITLE
Problem with study and can't give feedback from curator app

### ISSUE THREAD

**Issue by gaurav** [OpenTreeOfLife/feedback#234]
1. Study https://tree.opentreeoflife.org/curator/study/edit/pg_2519?tab=metadata appears to be incorrect: the tree included does not look like any of the trees in the paper. It's possible that a tree from another paper has been accidentally included here instead.
2. There should be a link to the feedback repo from the study page so that curators can flag them for review.

**Comment by kcranston** [comment]
Good suggestion re: adding feedback functionality to trees. Seems like we also might want a flag for 'I think there might be a problem with this study" so that these get checked before going into synthesis. 

As for that specific study - looks like the error is in TreeBASE, so whether it gets fixed here or in TreeBASE, want to make sure we both get the changes.

**Comment by mtholder** [comment]
closing this, as it seems to be a TreeBASE issue. and the tree is not in synthesis, and a note has been added to the study.
