### ISSUE TITLE
"Clade L": this is a rather odd taxon!

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#252]
This presumably needs either expanding or deleting
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/ottol@5247662/Clade-L](https://tree.opentreeoflife.org/opentree/argus/ottol@5247662/Clade-L) |
| Target node label | Clade L |
| Synthetic tree id | opentree5.0 |
| Synthetic tree node id | ott5247662 |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Supporting reference | n/a |

**Comment by jar398** [comment]
Indeed. If you want further information you will probably have to contact
the SILVA team, since the SILVA distribution provides no metadata on higher
level taxa. Pelin Yilmaz in particular is (or was) the main SILVA taxonomy
curator and would know where the name comes from. She may have given it
that name, or she may have found it in some publication.

**Comment by hyanwong** [comment]
I was more querying the lack of child taxa - but they may have been removed from the tree for some reason.

**Comment by jar398** [comment]
Follow the SILVA link from the tree browser to see what's supposed to be in
there. I agree that the lack of children is a problem. We're hoping to
include a lot more SILVA clusters in the future. All of them are
potentially good OTUs for integration since any sample used as an OTU in a
phylogenetic study might be placed in any cluster by sequence similarity.

**Comment by jar398** [comment]
Probably another case of https://github.com/OpenTreeOfLife/peyotl/issues/151 - let's see what it looks like in next synthesis.

**Comment by hyanwong** [comment]
Still in 12.3 (https://nexttree.opentreeoflife.org/opentree/argus/ottol@5247662/Clade-L) but this is a very minor issue

**Comment by mtholder** [comment]
will be fixed with https://github.com/OpenTreeOfLife/edOTTs/commit/ff01b28a993d85731219bdb8614c34a32cac14ea
