### ISSUE TITLE
Gnetophyta should be synonmised with Gnetidae (or higher)

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#279]
This node is empty, and should presumably be a parent of https://tree.opentreeoflife.org/opentree/opentree5.0@ott5422413/Gnetidae
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree5.0@ott10209/Gnetophyta](https://tree.opentreeoflife.org/opentree/opentree5.0@ott10209/Gnetophyta) |
| Target node label | Gnetophyta |
| Synthetic tree id | opentree5.0 |
| Synthetic tree node id | ott10209 |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Supporting reference | N/A |

**Comment by jar398** [comment]
https://github.com/OpenTreeOfLife/peyotl/issues/151  should make this node go away.

**Comment by jar398** [comment]
OTT 2.10 just copies what NCBI has:

```
Acrogymnospermae
    Gnetophyta
        environmental samples
        Gnetopsida
            all children suppressed (all gbif/irmng)
    Gnetidae
        Gnetales, other genera (ncbi)
```

Gneotphyta will be suppressed from the next synthetic tree since it has no non-suppressed descendants.

I don't know if the NCBI taxonomy is right. Maybe some of these Gnets should be merged. Would require research. I'd sort of prefer to wait hopefully until NCBI straightens it out. I guess I'll have to leave this as an open issue.
