### ISSUE TITLE
Some taxa not in synthetic tree, but have no apparent flags

### ISSUE THREAD

**Issue by uyedaj** [OpenTreeOfLife/feedback#286]
The following taxa are not in the synthetic tree but are not flagged either. This makes it impossible to know beforehand whether an induced subtree request including these taxa will fail or not. 

Eulemur fulvus (ott394961)
Pan troglodytes(!) (ott417950) 
Presbytis melalophos (ott406006)

**Comment by jar398** [comment]
You could use the v3/tree_of_life/node_info call to check on it first; if you get a 400 response it's not in the tree. Of course that is expensive if you have lots of ids to check.

We recently changed the API to make failures more brutal than they used to be in the way they handled missing ids.  It sounds like you would be helped if we recovered the previous behavior, where the service provided a list of ids not found in the tree, rather than a 400 response.  Does this sound correct?

An alternate design I'm considering is to have a service to validate a list of ids. You would call that first, and remove the missing ids before doing the tree_of_life call.

**Comment by uyedaj** [comment]
Yes, in general I would prefer fewer brutal failures in my life, I have enough already ;-)

Either way is fine, I tend to prefer the former (just return the tree + missing), but as long as the check is fast that would be fine. It seems like the 3 I listed are missing because of paraphyletic subspecies...is there any way to deal with this while still returning those species and not specifying a particular subspecies?

**Comment by mtholder** [comment]
We need a web service to give you this info, but in the interim the list of taxa that are not monophyletic in the tree can be found by parsing http://files.opentreeoflife.org/synthesis/opentree5.0/output/labelled_supertree/broken_taxa.json

**Comment by mtholder** [comment]
An issue describing this feature request is https://github.com/OpenTreeOfLife/germinator/issues/85

**Comment by jar398** [comment]
There is also an issue on dealing with invalid or obsolete ids (less
"brutal" behavior), here:
https://github.com/OpenTreeOfLife/germinator/issues/80

**Comment by mtholder** [comment]
fixed
