### ISSUE TITLE
This is indeed "not Puccinia triticina"

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#289]
The NCBI id for this taxon links to Puccinia triticina which is a fungus, not an archaean. Something has gone wrong with TNRS here, I presume
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/ottol@5574944](https://tree.opentreeoflife.org/opentree/argus/ottol@5574944) |
| Target node label | Not Puccinia triticina |
| Synthetic tree id | opentree5.0 |
| Synthetic tree node id | ott5574944 |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Supporting reference | http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=208348 |

**Comment by jar398** [comment]
This is fixed in the OTT2.10 draft. This was a taxonomy issue, not a TNRS issue. And @mtholder also does not like the "Not" in the name, which was my kludge for forcing this taxon to be separate from the real Puccinia triticina. This particular taxon (which is given an incorrect name by NCBI) will henceforth be called "cluster HP451821", which I presume will no longer come up in TNRS results.

**Comment by jar398** [comment]
I think you were actually asking for a change to the TNRS, under the assumption that there may be lots of other false positives like this one.  That would be nice, but fixing the taxonomy is much easier. If you come up with other cases suggesting that the TNRS is being too liberal in matching, please send them in. Once the new taxonomy is out I would like to just close this issue.

**Comment by jar398** [comment]
All I did was to replace 'Not X' with 'cluster Y' for the applicable records. Is that OK? I.e. can I close the issue?

**Comment by hyanwong** [comment]
Seems OK to me. Closing, and we can always reopen if future problems arise
