### ISSUE TITLE
Freshwater Ichthyosporeans 1 & 2, and Marine Ichthyosporeans 1 have no descendants

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#293]
These are from SILVA, but seem to have no subtaxa, and may simply be RNA sequence clusters. Not sure if anything need to be done about this or not, to if it is symptomatic of a general SILVA issue
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Yan Wong](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/opentree5.0@ott5251365/Freshwater-Ichthyosporeans-1](https://tree.opentreeoflife.org/opentree/argus/opentree5.0@ott5251365/Freshwater-Ichthyosporeans-1) |
| Target node label | Freshwater Ichthyosporeans 1 |
| Synthetic tree id | opentree5.0 |
| Synthetic tree node id | ott5251365 |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Supporting reference | N/A |

**Comment by jar398** [comment]
Hmm, if we got rid of this we'd have to get rid of most of SILVA...
This one does seem odd, since it's annotated as an 18S ribosomal RNA gene, but the SILVA tree we use is based on 16S; but the annotations are often wrong.

In the OTT 2.10 draft this cluster is not flagged 'unclassified' any more, so it will be available as an OTU and will show up in the synthetic tree. The earlier 'unclassified' flag was a mistake.

I think I'm going to mark this 'wontfix'. This is respecting Laura Katz's request from a few years back that the synthetic tree expose as much microbial diversity as possible. (There are another 300,000 clusters like this one waiting in the wings.) But is there more that you know about this group to suggest that SILVA's taxonomic placement and/or description is wrong? E.g. is there reason to think freshwater ichthyosporeans don't exist? The SILVA taxonomy curator (probably Pelin Yilmaz) had enough faith in this cluster to invent a name for a group that would contain it.

**Comment by hyanwong** [comment]
I think the problem is partially with the name. These are clearly temporary made-up clade names. I doubt they have much taxonomic authority behind them (but I could be wrong). It's odd that they contain no species in the synthetic tree: I suspect that either a number of ichthyosporeans identified by other studies belong in these groups. But it's not my area. I can ask an expert who I know (Iñaki Ruiz-Trillo)

**Comment by jar398** [comment]
This group does have a member, as you can see in the SILVA taxonomy
browser. NCBI gives it a name with the word 'uncultured' in it.  Uncultured
taxa from NCBI only are filtered out as 'unclassified,' but since SILVA
classifies them they occur unflagged in the taxonomy - not in 2.9, which
has a bug, but it will appear in 2.10.

For 'microbes' we use the taxonomy from SILVA (on the advice of Laura
Katz), which, as I say, is the work of one or a small number of people.
SILVA made a big phylogenetic tree based on 16S sequences organized into
clusters, and then, partly based on known groups, gave names to internal
nodes that were well supported.  But there were a lot of groups left over
for which there was phylogenetic signal but no name.  So they just made up
names, as you say.  Since Open Tree is about phylogenetic relationships and
nomenclature is not a primary concern, SILVA seems a good match to the
project.

I suppose that if the SILVA team cared a lot about proper description they
would research each group to figure out its biology so that it could be
described and given a 'respectable' name. That sounds really really hard to
me. The phylogeny is way ahead of taxonomy and I doubt they are funded to
do anything other than sequence-based taxonomy.

I can't say anything about the quality of the phylogeny, but I think they
are being conservative; many nodes in the taxonomy are big polytomies,
which to me says they're being conservative in saying which nodes are well
enough supported to deserve names.

**Comment by mtholder** [comment]
the empty groups will be fixed with https://github.com/OpenTreeOfLife/edOTTs/commit/eaf0da51bd01dcc30327c2a8036c76a4aff01cb3 Freshwater Ichthyosporeans 1 was left because it has descendants.
