### ISSUE TITLE
Hemitragus hylocrius is synonym of Nilgiritragus hylocrius 

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#296]
should be merged with https://tree.opentreeoflife.org/opentree/argus/ottol@4118935/Nilgiritragus-hylocrius
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Yan Wong](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/opentree5.0@ott203064/Hemitragus-hylocrius](https://tree.opentreeoflife.org/opentree/argus/opentree5.0@ott203064/Hemitragus-hylocrius) |
| Target node label | Hemitragus hylocrius |
| Synthetic tree id | opentree5.0 |
| Synthetic tree node id | ott203064 |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Supporting reference | http://www.iucnredlist.org/details/9917/0 |

**Comment by jar398** [comment]
The species is duplicated in GBIF and IRMNG, under the two different names.
They can be merged, but NCBI and IUCN are fighting here over what the genus should be: NCBI says Hemitragus, while IUCN says Nilgiritragus. The simplest fix is merging using NCBI's names. Otherwise we start down the path of a more thorough review of the GBIF genera in Bovidae that are not in NCBI subfamilies in order to do a proper merge of the GBIF and NCBI classifications. That's pretty low priority for me, but someone else should feel free...

I think I will wait to see if the new GBIF release sheds light on this - it probably does.

**Comment by hyanwong** [comment]
_Nilgiritragus hylocrius_ has now vanished from OTT 3.2, although the genus (barren) still exists. Annoyingly this means that the OpenTree doesn't know about the synonymy, but that's better than having duplicates present, so I'm closing this.
