### ISSUE TITLE
Species of the genus Pygophora are flies, not barnacles

### ISSUE THREAD

**Issue by EwersAquaGenomics** [OpenTreeOfLife/feedback#297]
All species of the genus Pygophora are Diptera (flies), not acrothoracican barnacles. They should be removed from the Acrothoracica. Pygophora used to be an acrothoracican order, but is no longer valid.
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Christine Ewers-Saucedo](https://github.com/ewersSaucedo) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/opentree5.0@ott363891/Acrothoracica](https://tree.opentreeoflife.org/opentree/argus/opentree5.0@ott363891/Acrothoracica) |
| Target node label | Acrothoracica |
| Synthetic tree id | opentree5.0 |
| Synthetic tree node id | ott363891 |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Supporting reference | http://www.sciencedirect.com/science/article/pii/S1055790316300069 |

**Comment by jar398** [comment]
Looks to me like there are no longer any flies under the crustacean Pygophora any more, but maybe I missed some. But crustacean Phygophora still exists in OTT because it's in NCBI taxonomy, which is our barnacle taxonomy source. If someone provides me an improved barnacle taxonomy (Lin's or any other) in machine readable form, I can incorporate it. That can be done by reopening this issue or submitting a new one.

https://tree.opentreeoflife.org/taxonomy/browse?id=363893
