### ISSUE TITLE
Ascomycetes should probably be synonymised with ascomycota

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#300]
At the moment this is an empty node
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Yan Wong](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/ottol@5281392/Ascomycetes](https://tree.opentreeoflife.org/opentree/argus/ottol@5281392/Ascomycetes) |
| Target node label | Ascomycetes |
| Synthetic tree id | opentree6.1 |
| Synthetic tree node id | ott5281392 |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Supporting reference | https://en.wikipedia.org/wiki/Ascomycota |

**Comment by jar398** [comment]
All descendants are either extinct or speciesless, so this group should be suppressed from synthesis according to the new peyotl logic. I think that will address your complaint that there is an empty node, but it won't actually cause the taxonomy to make sense.

But this corner of the taxonomy (fossil fungi) is a tangled mess due to IF, WoRMS, and IRMNG all doing slightly different things. I'm going to put off fixing this for the most part, although I can do a few small things like getting rid of empty 'incertae sedis' containers. https://github.com/OpenTreeOfLife/reference-taxonomy/issues/245
