### ISSUE TITLE
Only 2 extant species of Isurus

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#302]
So the majority of species here, apart from Isurus oxyrinchus and Isurus paucus are synonyms or should be marked extinct.
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Yan Wong](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/opentree6.1@ott500595/Isurus](https://tree.opentreeoflife.org/opentree/opentree6.1@ott500595/Isurus) |
| Target node label | Isurus |
| Synthetic tree id | opentree6.1 |
| Synthetic tree node id | ott500595 |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Supporting reference | http://www.fishbase.se/summary/FamilySummary.php?ID=9 |

**Comment by hyanwong** [comment]
In fact, this issue goes further: a large number of sharks on the synth tree are fossils but not identified as such. https://tree.opentreeoflife.org/opentree/argus/ottol@3595175/Lamnidae lists 52 descendant tips, but there are only 5 extant species in this family (http://www.fishbase.se/summary/FamilySummary.php?ID=9). So >90% of the species have been mistakenly included.

**Comment by jar398** [comment]
Yes, I'd say this is quite serious. It has to do with inclusion of species from IRMNG, many of which are fossil species lacking the fossil flag. I'm consulting with Tony Rees about this issue, but I suspect we will just have to hide most of the IRMNG-only species, even if they might be extant.

**Comment by hyanwong** [comment]
Thanks. Glad it has been noticed. I suspect sharks are a particular problem because the teeth fossilise well.

**Comment by hyanwong** [comment]
This is now _much_ better in OpenTree 7, with only 2 taxa out of 8 at https://devtree.opentreeoflife.org/opentree/argus/ottol@3595175/Lamnidae being misidentified fossils (_Squalicorax_ & _Carcharodon angustidens_). @jar398 looked into _Carcharodon angustidens_ and found 

> from the information I have there’s no way to know Carcharodon angustidens is extinct (the GBIF database knows it comes from 2 sources, IRMNG and PaleoDB, and it knows when it lived & went extinct, but the GBIF dump file only captures one source, IRMNG)

So I guess this issue can be closed, unless it mutates into another issue "try to get GBIF to provide extinctness data in dump file, even when it is only provided by one of multiple sources"

**Comment by hyanwong** [comment]
FWIW, a decent heuristic seems to be that leaf taxa with a single name and no epithet are usually fossils. See https://devtree.opentreeoflife.org/opentree/opentree7.0@ott32038/Lamniformes where you can additionally spot _Pseudodontaspis_, _Synodontaspis_, and _Scapanorhynchus_, which I can pretty confidently say are fossils, even though I haven't investigated.

**Comment by jar398** [comment]
I _think_ GBIF provides a DwCA for PaleoDB (so we wouldn't have to talk to
PaleoDB directly to get it) - and for all of its sources. If we processed
this, I conjecture, we will get lots of good extinct annotations. (The taxa
themselves will be in the new GBIF dump, which we'll import at some point.)
I haven't checked to be sure; but I _think_ that all the information you
can see in the GBIF interface, is available by one download or another of
datasets that GBIF provides publicly; and extinctness info is visible, so I
think we can get it.

Research needed.

**Comment by jar398** [comment]
see #206

**Comment by jar398** [comment]
Pseudodontaspis contains a single species, which is known to be extinct: https://devtree.opentreeoflife.org/taxonomy/browse?id=4139168
OTT used to infer that the genus is extinct, from the fact that all species are extinct (that's why I had to add Homo sapiens sapiens - to prevent Homo from going away!). Not sure why it isn't doing this now, but in any case the problem with extinct genus tips would be fixed if this peyotl bug were fixed:
https://github.com/OpenTreeOfLife/peyotl/issues/151
Since @mtholder said he preferred this be dealt with this in peyotl, I'm not going to repair it in OTT.

**Comment by jar398** [comment]
Isurus is [looking pretty](https://tree.opentreeoflife.org/taxonomy/browse?name=Isurus) good to me, and this is due to changes in general logic, not a patch. We're down to five species now, with two ghosts (Squalicorax and Carcharodon angustidens) that I'll take care of separately. So I think I can close this. But please let me know if you see more things like this.

Re getting paleodb from GBIF, which would take care of the two ghosts, we'll track that at https://github.com/OpenTreeOfLife/reference-taxonomy/issues/206 .
