### ISSUE TITLE
Opheliida is empty and a 'nomen dubium'

### ISSUE THREAD

**Issue by OneZoomDeveloper** [OpenTreeOfLife/feedback#305]
This clade is empty in the synth tree, and listed as superfluous by the world polychaete database
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [OneZoom Developer](https://github.com/OneZoomDeveloper) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/ottol@955755/Opheliida](https://tree.opentreeoflife.org/opentree/argus/ottol@955755/Opheliida) |
| Target node label | Opheliida |
| Synthetic tree id | opentree6.1 |
| Synthetic tree node id | ott955755 |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Supporting reference | http://www.marinespecies.org/polychaeta/aphia.php?p=taxdetails&id=891 |

**Comment by jar398** [comment]
This is another case of https://github.com/OpenTreeOfLife/peyotl/issues/151

**Comment by hyanwong** [comment]
My guess is that this is a typo for https://tree.opentreeoflife.org/opentree/argus/ottol@336915/Opheliidae

**Comment by jar398** [comment]
Looks like an NCBI problem, of a sort we've seen many times: detritus left
over after a reclassification.

IRMNG has family Opheliidae in order Opheliida (in class Polychaeta); looks
like older classifications had Opheliida in this sense.
NCBI has family Opheliidae sibling to order Opheliida in subclass Scolecida
in class Polychaeta.

NCBI's only use of Opheliida is as a container of BOLD sequences, which is
why it ends up empty in synthesis. My guess is it was seen to be
polyphyletic by the new classification, but the old classification didn't
get deleted.

Since NCBI is similar to WPD (= WoRMS), both reflecting what seems to be a
modern rearragement of Scolecida, the thing to do is probably to merge the
residual Opheliida into Scolecida (since we don't know what family they
would belong to).​ Odd that WPD would get rid of all the orders, and put
families directly in a subclass, but that's what it does:

http://www.marinespecies.org/aphia.php?p=taxdetails&id=183607

NCBI for comparison:

http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Undef&id=105387&lvl=3&keep=1&srchmode=1&unlock

**Comment by hyanwong** [comment]
Thanks for hunting down.

**Comment by mtholder** [comment]
closed as an NCBI issue
