### ISSUE TITLE
Synonym of Notorynchus cepedianus (ott 1077217)

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#310]
Should be merged with ott 1077217, which is in a slightly different part of the tree.
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [Yan Wong](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/opentree6.1@ott290409/Notorynchus-maculatus](https://tree.opentreeoflife.org/opentree/argus/opentree6.1@ott290409/Notorynchus-maculatus) |
| Target node label | Notorynchus maculatus |
| Synthetic tree id | opentree6.1 |
| Synthetic tree node id | ott290409 |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Supporting reference | https://en.wikipedia.org/wiki/Broadnose_sevengill_shark |

**Comment by jar398** [comment]
Catalog of fishes says:

maculatus, Notorynchus Ayres [W. O.] 1855:72 [Proceedings of the California Academy of Sciences (Series 1) v. 1 (pt 1); ref. 159] California, U.S.A. No types known. •Valid as Notorynchus maculatus Ayres 1855 -- (McAllister 1990:28 [ref. 14674]). •Synonym of Notorynchus cepedianus (Péron 1807) -- (Compagno 1984:22 [ref. 6474], Springer 1990:4 [ref. 19315], Gomon et al. 1994:89 [ref. 22532], Mecklenburg et al. 2002:84 [ref. 25968], Espinosa Pérez et al. 2004:89 [ref. 27705], Hoese & Gates 2006:136 [ref. 28997], Castro 2011:38 [ref. 31457], Dyldin 2015:43 [ref. 34524], Del Moral-Flores et al. 2016:57 [ref. 34398], Compagno 2016:1151 [ref. 34544]). Current status: Synonym of Notorynchus cepedianus (Péron 1807). Hexanchidae. Habitat: marine.

Correction sent to NCBI. Not yet fixed in OTT.

**Comment by jar398** [comment]
From: info@ncbi.nlm.nih.gov  
Dear Colleague,

Thank you for contacting us with this information. The Taxonomy staff has merged Notorynchus maculatus with Notorynchus cepedianus as a synonym.

**Comment by hyanwong** [comment]
Synonymised in 11.4 and 12.3
