### ISSUE TITLE
Galapagos iguanas are not extinct!

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#345]
Currently this

https://tree.opentreeoflife.org/opentree/argus/ottol@735227

is not on the synth tree, apparently because *Conolophus* is wrongly labelled 'extinct'

https://tree.opentreeoflife.org/taxonomy/browse?id=735227

I hope they aren't yet!

**Comment by hyanwong** [comment]
A bit of digging reveals that this is probably because there are two IRMNG entries, one of which is the correct one (and flagged as extant), and one of which is a name conflict with a fossil Condylarth species (http://www.marine.csiro.au/mirrorsearch/ir_search.taxon_info?id=1415243). Hmm. Not sure how you are meant to deal with this, TBH? @jar398 any ideas?

**Comment by jar398** [comment]
IRMNG has two records, different authors, both apparently accepted, one extinct and the other extant. Smasher doesn't handle this situation well, as it looks like a contradiction.

Turns out Conolophus Zhang, 1978 is a fossil mammal genus containing no species. We don't have a good way to deal with homonyms in this situation (within the same 'separation taxon', when one of the two doesn't have children).

Options: force the two to be separate (this is currently a pain in the butt), or prune the mammal from the taxonomy, or rename it. I like the latter, and it looks like someone else did too:

http://en.cnki.com.cn/Article_en/CJFDTOTAL-GJZD198003013.htm

IRMNG record: http://irmng.org/aphia.php?p=taxdetails&id=1415243

**Comment by hyanwong** [comment]
Agree. How easy is it to rename, though? Do you have to do it at source in IRMNG? Or can it be hacked as an exception in OpenTree?

**Comment by jar398** [comment]
To see the level of difficulty, peruse one of the project's dirty secrets:

https://github.com/OpenTreeOfLife/reference-taxonomy/blob/master/amendments.py

The command to use in this case, I think, is 'clobberName'. 'rename' leaves a synonym behind, and that might just perpetuate the current state of affairs.

**Comment by TonyRees** [comment]
Conolophus Zhang, 1978 (fossil mammal genus) has now been changed from "accepted" to "synonym" in the current version of IRMNG (synonymized with its replacement name Minchenella Zhang following PaleoBioDB) so that should be fixed in the next version of the IRMNG export file. Unfortunately that will still leave a lot of unresolved homonyms at this time, some of which could be fixed via a bulk comparison e.g. with PaleoBioDB which I will think about one day...  Often IRMNG has information about proposed replacement names for genera but (till now at least) these have not been uncritically accepted because sometimes the replacement name itself is not valid, or the original genus has subsequently been synonymized with something else, and so on. There is a default "accepted" status for names in the new version of IRMNG at VLIZ for anything that is not a known synonym or some other cases at this time, which is a bit sub-optimal (I have suggested a "not known" option but this is not currently supported).

(Only another xx thousand similar cases to treat...)

**Comment by TonyRees** [comment]
Also I have not checked your "major conflict indicator" groups but I have done similar things in constructing IRMNG, in which mammals and reptiles (and amphibia and birds and fishes) are *not* in the same group (hint hint...)

**Comment by jar398** [comment]
The major groups form the 'separation taxonomy' and I've been trying to keep it as simple as possible, since lining it up with the sources is a manual operation whenever the group names vary - this is an emornous headache even with only 30 taxa as it has at present. Chordates are tiny and it has no resolution for it. Maybe it is time to add major monophyletic vertebrate groups to it, I don't know... it seems like a slippery slope since if you added every mammal-sized group you'd have a very large separation taxonomy, which would end up being a huge headache.

I wish I had some idea if this genus is special in some way, or if there are thousand others like it lurking, that I haven't seen.

I think it's worth thinking laterally. There has to be a better way. I have [an idea](https://en.wikipedia.org/wiki/Continuous_function#Continuous_functions_between_topological_spaces) on how to dispense with the separation taxonomy, but haven't had time to implement it.

**Comment by jar398** [comment]
(hmm, I think maybe you are thinking of 'major_rank_conflict', in which case it doesn't mean what you think it does... it is just a synonym for 'incertae sedis' (or 'unallocated').  The 'major taxa' used for preserving homonyms are simply the taxa in the 'separation taxonomy'.)

**Comment by TonyRees** [comment]
Hi Jonathan, the genus is only "special" so far as I can tell in that both homonyms fall within the same major separation group, which is a smaller subset, also the junior homonym is (was) not flagged as non-current/unaccepted. How many may be lurking... well if there are around 70k genus level homonyms (affected names), of which maybe 30k are valid, 40k invalid (with a small subset nomina nuda/misspellings that you already discard), at a guess perhaps 10k of the invalid ones are already synonymized (leaving 30k), of which probably 90%+ may be in different "separation groups" - so the problem possibly affects perhaps <3k genus names in IRMNG at this time (if that helps).

**Revision - actually that would be <6k distinct taxa with <3k distinct names since we cannot distinguish the correct from the incorrect "accepted" names in this case. However correctly flagging the notional 3k junior homonyms as such would resolve it I am guessing.**

I cannot really follow your "idea" involving "Continuous functions between topological spaces" but I actually think the idea of "separation groups" is a good practical solution. In fact if I were still doing this I would probably adjust my last-used list (see "Group to search" option at http://www.cmar.csiro.au/datacentre/irmng/) a little but not too much.

**Comment by TonyRees** [comment]
Of course from a larger perspective, this just indicates that IRMNG is doing its job and alerting you to a potential ambiguity regarding the genus name Conolophus, plus any species thereof - in other words some additional effort may be required to determine which of any of the latter are extant reptiles with potentially a currently valid name, and which are fossil mammals with an invalid name...

**Comment by hyanwong** [comment]
@jar398: just wondering if Conolophus is going to be reinstated in the next synth tree release?

**Comment by jar398** [comment]
I usually do fixes like this in batches, and haven't gotten to it yet. I generally do fixes like this in batches but will bump the priority of this one. So, probably.

**Comment by hyanwong** [comment]
Just noticed that _Conolophus_ is still missing from the synth tree (both devtree and production). Since this is flagged as "fixed in taxonomy draft", am I to assume that it will magically appear on the next taxonomy release? Possible a Q for @jar398 although I know he's no longer heavily involved.

**Comment by TonyRees** [comment]
Hi all, FYI the _Conolophus_ issue was fixed in IRMNG a couple of years ago as advised above, see http://www.irmng.org/aphia.php?p=taxlist&searchpar=0&tComp=is&tName=Conolophus&action=search, so would be picked up in the 2018 and 2019 releases. Also in the latest release, "orphan" names from Nomenclator Zoologicus not in other IRMNG sources (which includes the bulk of unresolved homonyms in IRMNG) are now flagged "uncertain" in the download which is a lot better than the previous "accepted". Just in case this helps with respect to re-importing any new IRMNG data (which could remove some headaches I think).

**Comment by mtholder** [comment]
Thanks for the info @TonyRees . I just have to apologize for the slowness in getting the next version of the taxonomy out. I'm currently working on the synthesis tweaks needed to get fossils on the tree. I'll be returning to taxonomy when that work is completed.

**Comment by TonyRees** [comment]
That's OK, I know these things take time, and also are often non-trivial once you scratch the surface...

**Comment by jar398** [comment]
I flagged it as fixed, so I was very confident that it will be fixed next time around. I'll bet you a beer it will be.

**Comment by hyanwong** [comment]
@jar398 happy to buy you a beer anyway. I think I owe you a caseful.

Thanks for the feedback everyone. Looking forward to the new taxonomy.

**Comment by hyanwong** [comment]
Seems all corrected now. `Conolophus grandis` (the condylarth) is marked as extinct in the taxonomy. The 3 Galapagos iguanas are correctly showing on the tree (11.4 and 12.3). I owe @jar398 a beer.
