### ISSUE TITLE
Why did Heterostichus rostratus (ID 257317) become extinct?

### ISSUE THREAD

**Issue by dbarneche** [OpenTreeOfLife/feedback#346]
Up until a couple of weeks ago, downloading a tree from within `R` using `rotl::tnrs_match_names` returned no flags for this species, but now is is flagged as EXTINCT_INHERITED.

**Comment by jar398** [comment]
Probably a problem introduced in the move from version 2.10 to version 3.0.  This is very similar to issue #345.  There are two records for this genus name from IRMNG, with different authorities. But they are both in Actinopterygii so they get merged.  Probably the one you intend is the one that's not extinct.

Heterostichus Wagner, 1860 in Amiiformes, extinct
http://www.marine.csiro.au/mirrorsearch/ir_search.taxon_info?id=1343142

Heterostichus Girard, 1854 in Perciformes, extant
http://www.marine.csiro.au/mirrorsearch/ir_search.taxon_info?id=1343141

I'll try to fix this for version 3.1.

**Comment by dbarneche** [comment]
Yep, I was referring to the extant taxon.
Thanks very much for your quick response!

**Comment by TonyRees** [comment]
Hi Jonathan, just a reminder that IRMNG links of the type

http://www.marine.csiro.au/mirrorsearch/ir_search.taxon_info?id=1343142

need to be replaced with e.g.

http://www.irmng.org/aphia.php?p=taxdetails&id=1343142

because the former will be deprecated at some point; the new-style links are at the new location (VLIZ), which is the instance that is being updated on an ongoing basis with new information as it comes to hand, errors corrected, etc. (by contrast, the CSIRO version is "frozen" as at 2014).

Of course you know this :)

Regards - Tony

**Comment by jar398** [comment]
Yes, I know this, and we'll switch over at some point. An advantage of the deprecated links is that they show the IRMNG that was input to OTT synthesis, as opposed to a more recent one. So while it may not be as 'good', it is better for the purpose of debugging OTT.

**Comment by jar398** [comment]
also the CSIRO version has a more compact display, and seems to show more information.

**Comment by TonyRees** [comment]
OK, thanks for that perspective. The "new" display follows the templates established for WoRMS etc. at VLIZ, so is hard to change, although I guess the new custodians may be receptive to feature requests...

Cheers - Tony

**Comment by mtholder** [comment]
the issue for this taxon will be fixed by https://github.com/OpenTreeOfLife/edOTTs/commit/253d4d08d951510109f30ef96f5d9a722fc87482
