### ISSUE TITLE
OTU mapping defaults to preferred trees

### ISSUE THREAD

**Issue by snacktavish** [OpenTreeOfLife/feedback#35]
It is  a bit confusing that OTU mapping defaults to preferred trees, especially b/c there aren't any for most studies, and it makes it look like there aren't any tips. Can it default to all trees instead?

**Comment by jimallman** [comment]
Agreed that it's currently pretty disappointing as the default. I was concerned about studies with many trees, since the full list of OTUs could present an overwhelming (and unnecessary) amount of work. Maybe I could modify it so that the default filter is 'All trees' only when there are no preferred trees?

**Comment by josephwb** [comment]
I think we'd always want it to be all trees. For one, the trees are _probably_ all going to have the same tips (unless they use different labelling in different analyses).

**Comment by chinchliff** [comment]
I agree, it's quite unlikely that the otu set of all trees would represent
significantly more than that of just the preferred tree. It seems like
there would actually be more requests to the TNRS if we did trees
separately because many queries would be duplicates. We also want to
maximize the value of curation effort, which to me suggests that we should
attempt to apply any mapping information that curators are willing to
provide to as many trees as possible. Preferred trees will be used for
synthesis, but any/all trees may be useful for other analyses.

**Comment by jimallman** [comment]
> It seems like there would actually be more requests to the TNRS if we did trees 
> separately because many queries would be duplicates. We also want to 
> maximize the value of curation effort, which to me suggests that we should 
> attempt to apply any mapping information that curators are willing to 
> provide to as many trees as possible.

Keep in mind that OTUs may well be shared in multiple trees. The filter is aware of this and gathers all OTUs in the chosen trees. So an OTU might well appear in both ‘Preferred trees’ and ‘Non-preferred trees’.

Once an OTU is mapped for one, it’ll show as mapped for all. So this shouldn’t create extra work unless there are “extra” (duplicate) OTUs in different trees. So we should never be adding extra work based on the chosen filter.

**Comment by chinchliff** [comment]
I see. That does reduce the redundancy. I do think there is value in
defaulting to asking the curator to deal with all the OTUs for the study at
once. If they choose to do only the preferred tree, that's fine, but if
they do map all the otus for all trees (probably not much more work for
them), those other trees become useful for analyses other than synthesis.

**Comment by jimallman** [comment]
Understood. I'll make this change shortly.

**Comment by jimallman** [comment]
Fixed in commit 3c0cec84ebfc7115b46fc2c8621625fa2cb92125
