### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#370]
I'm interested in this area and I am trying to determine if this project is still active. The latest links to the Blog area yield results which don't have a date and the last dated entry is for spring of 2016. If this effort is still being conducted, how do I find information about the project and what is currently being done?

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Philip May](mailto:pwmay1@gmail.com) 
Upvotes   |   0 
URL   |   [/contact](https://tree.opentreeoflife.org/contact) 
Target node label   |    
Synthetic tree id   |    
Synthetic tree node id   |    
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   None

**Comment by mtholder** [comment]
Hi Philip, yes the project is still active (though not as many people are working on it as last year).  We are seeking more funding and hope to continue to support it for years to come. 

The software developers use an open chat at https://gitter.im/OpenTreeOfLife/public to discuss issues. So that is probably the best place for a short query, but using the email list is also fine.
The lists are described at: https://tree.opentreeoflife.org/contact


all the best,
Mark
