### ISSUE TITLE
Musca tenax is synonym of Eristalis tenax

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#371]
An error from GBIF (now reported at
https://github.com/gbif/portal-feedback/issues/746 ) and also IMNRG 

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Yan Wong](https://github.com/hyanwong) 
Upvotes   |   0 
URL   |   [tree.opentreeoflife.org/opentree/argus/ottol@5853691/Musca-tenax](https://tree.opentreeoflife.org/opentree/argus/ottol@5853691/Musca-tenax) 
Target node label   |   Musca tenax 
Synthetic tree id   |   opentree9.1 
Synthetic tree node id   |   ott5853691 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   https://bie.ala.org.au/species/urn:lsid:biodiversity.org.au:afd.taxon:a599001c-6f76-41dd-a2ad-b1770a889266#names

**Comment by hyanwong** [comment]
IRMNG correction presumably via @TonyRees

**Comment by TonyRees** [comment]
@hyanwong RE gbif/portal-feedback#746 Actually I do not know of a report of the error to IRMNG, but I can fix it. From a little literature sleuthing I find that Musca tenax is indeed a synonym of Eristalis tenax (in fact it is the type species of the latter well established genus), and presently I have IRMNG records for both as accepted taxa (M. tenax from CoL / www.diptera.org via CoL 2006 version, E. tenax from the New Zealand Organisms Register in 2007). The synonym assertion is now given in www.diptera.org and therefore presumably in more recent versions of CoL, but I have not generally updated species names from the latter since 2006 (and it may be a while before anything is done in that regard).

**Comment by TonyRees** [comment]
OK, fixed now in IRMNG. However scrutinizing the remaining 1.9m species names (minus 1) in IRMNG for currency on an ongoing basis will probably be a task for others down the track...

**Comment by hyanwong** [comment]
@TonyRees thanks a lot. And yes, one-by-one is not the right way to approach this problem. I simply brought up this (reasonably conspicuous) example at the behest of one of our users.

**Comment by TonyRees** [comment]
@hyanwong No problem, it is always good to fix conspicuous or even less conspicuous issues as notified, while being aware that it/they may be something of a drop in the ocean when there are other elephants in the room (such as my CoL data import being >10 years out of date).

**Comment by hyanwong** [comment]
Still present in 11.4 but fixed in 12.3 (presumably with the new OTT 3.2)
