### ISSUE TITLE
Duplicate Rozella species

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#374]
Nearly all the species in https://tree.opentreeoflife.org/opentree/argus/ottol@5975857/Rozella-genus-in-Discicristoidea- are duplicates of those in https://tree.opentreeoflife.org/opentree/argus/ottol@958913/Rozella-genus-in-kingdom-Fungi- which is probably a result of some taxonomies placing this group within Fungi and some as the fungal sister group. Only one species, https://tree.opentreeoflife.org/opentree/opentree9.1@ott358358/Rozella-allomycis is placed via phylogeny, so this should probably be where all the other Rozella species are placed too, and the node at https://tree.opentreeoflife.org/opentree/argus/ottol@5975857/Rozella-genus-in-Discicristoidea- should be deleted.

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Yan Wong](https://github.com/hyanwong) 
Upvotes   |   0 
URL   |   [tree.opentreeoflife.org/opentree/argus/ottol@5975857/Rozella-genus-in-Discicristoidea-](https://tree.opentreeoflife.org/opentree/argus/ottol@5975857/Rozella-genus-in-Discicristoidea-) 
Target node label   |   Rozella 
Synthetic tree id   |   opentree9.1 
Synthetic tree node id   |   ott5975857 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   N/A

**Comment by jar398** [comment]
Darnit, Rozella has always been a problem since some authors put it in Fungi and some don't (or alternatively: some give the name 'Fungi' to a group that includes Rozella and others give the name 'Fungi' to a smaller group that doesn't). And since Fungi is a barrier to name matching, duplications happen if this isn't dealt with at the right time.

This will be easy to fix with a new taxonomy build. Thanks for reporting it.

**Comment by mtholder** [comment]
fixed in previous OTT
