### ISSUE TITLE
Species selection

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#379]
For example, I want to choose the species of A,B,C,D,E,F,G to see their evolutionary relationships. I can use the mouse to select these several species, and then display only the selected. So the evolution relationship between these species will be very clear

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [JYL](mailto:jiayanglei) 
Upvotes   |   0 
URL   |   [tree.opentreeoflife.org/opentree/argus/opentree9.1@ott335938/Vetigastropoda](https://tree.opentreeoflife.org/opentree/argus/opentree9.1@ott335938/Vetigastropoda) 
Target node label   |   Vetigastropoda 
Synthetic tree id   |   opentree9.1 
Synthetic tree node id   |   ott335938 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   None

**Comment by kcranston** [comment]
Thanks for the feedback! You should take a look at the Phylotastic project: http://phylotastic.org/ 

In their web portal, you can create trees for specific lists of species. They use our phylogeny as one of the sources (i.e. they have built this feature so that we don't have to!). We should have a more prominent link to Phylotastic on our pages.
