### ISSUE TITLE
bibliographic references

### ISSUE THREAD

**Issue by snacktavish** [OpenTreeOfLife/feedback#38]
The refs with the links look so shiny and great! 
Just two q's: 
Is it really only the trees included in synthesis (as labelled at the top)? It looked like it might be all of them. 
Can they be sorted alphabetically?

**Comment by jar398** [comment]
There are 327 of them. So those are just the ones in synthesis, not the
whole set.

Sorting is a good idea. Almost all references are first author last name
first; a few will need to be fixed.

**Comment by jimallman** [comment]
Actually, I had sorting code to do just that, but it's commented out to avoid messing up a default sort based on "importance":

```
        # TODO: sort these alphabetically(?) and render in the page
        ## contributing_studies.sort(key = lambda x: x.get('ot:studyPublicationReference'))
        # NO, apparently they're pre-sorted to reflect the importance of each study
```

But I'm looking at [the **getSynthesisSourceList** method](https://github.com/OpenTreeOfLife/treemachine/blob/master/src/main/java/opentree/plugins/GoLS.java#L214) and there's no sign (to me) of this sorting. @blackrim, was I mistaken in my comment above?

**Comment by jar398** [comment]
I think the list as returned by the service is in order of priority in
synthesis.  That's why taxonomy is last in the list.  The ordering is
specified by the tree lists in gcmdr and preserved internally by
treemachine. (at least that's how I've understood it to work, Stephen might
correct me.)

Hate to pile on requests, but it would be nice to be able to see either
order...
