### ISSUE TITLE
Error in handling of homonyms

### ISSUE THREAD

**Issue by uyedaj** [OpenTreeOfLife/feedback#380]
The genus Cnemidophorus is a homonym for a group of lizards and a defunct name for a group of weevils. In OpenTree, the weevil genus has 3 members, all of them should be lizards.
Cnemidophorus (genus in the Protostomia) Ottid: 5265697
Children:
Cnemidophorus duellmani, OTT: 6237981
Cnemidophorus pyrrhogularis, OTT: 6237982
Cnemidophorus ruatanus,OTT: 6237983

None of these species appear in the GBIF taxonomy from which the Protostome (weevil) genus Cnemidophorus is taken from (https://www.gbif.org/species/1179544).

**Comment by mtholder** [comment]
Thanks for reporting this, @uyedaj . We need to rebuild the taxonomy from a newer download of GBIF in the 29 July, 2016 dump of GBIF these were erroneously listed as weevils (ids 8660003, 8444638, and 8540384 respectively), but that has been corrected in the most recent GBIF taxonomy. 
I'll leave this issue open, so that we remember to double check it when the taxonomy is rebuilt.
