### ISSUE TITLE
Annelida

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#382]
I notice on the.synthetic tree annelids are not on there and when I.look for them on the database it thinks they are extinct

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   Danielle Wilson 
Upvotes   |   0 
URL   |   [/contact](https://tree.opentreeoflife.org/contact) 
Target node label   |    
Synthetic tree id   |    
Synthetic tree node id   |    
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   opentree.org

**Comment by opentreeapi** [comment]
I tried to link to opentree.org because a website was required and it showed an error message

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   Danielle Wilson 
Upvotes   |   0

**Comment by opentreeapi** [comment]
Here is the link I was trying to get to

https://tree.opentreeoflife.org/opentree/opentree9.1@ott155737/Lophotrochozoa


================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   Danielle Wilson 
Upvotes   |   0

**Comment by mtholder** [comment]
Hi Danielle,
thanks for reporting the issue. Annelids are not flagged as extinct in our taxonomy. The taxonomy page for them is https://tree.opentreeoflife.org/taxonomy/browse?name=Annelida (I do realize that the "e.g. extinct" text at the top of the page may make it look like they are flagged that way, but that is intended as explanatory note to show what the flags look like.

I think you can find most of them from navigating around: https://tree.opentreeoflife.org/opentree/opentree9.1@mrcaott24ott102965/Myzostomida--Clitellata

 I think that they don't show up in the tree because the current tree does not put Myzostomida with the rest of the Annelids. Taxonomies vary on what goes inside Annelida. If you are curious about the details, there are a couple of Open Tree GitHub issues where this is discussed: https://github.com/OpenTreeOfLife/germinator/pull/112 and https://github.com/OpenTreeOfLife/reference-taxonomy/issues/238

The longer term solution is for the browser to show you the relevant part of the tree when a taxon is not monophyletic. This has been a long standing issue (see https://github.com/OpenTreeOfLife/germinator/issues/85 ). The good news is that we are pretty close to having a new tool for serving up the synthetic tree that would fix this. Unfortunately, it still needs a bit more testing before being deployed.

**Comment by opentreeapi** [comment]
Thank you. I didn't know Annelida wasn't monophyletic. Thank you for teaching me. I think a Tree of Life should consist of monophyletic lineages and try and stay away from paraphyletic and polyphyletic lineages. I am not a professional taxonomist I just like to research this kind of thing. It's interesting to me.

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   Danielle Wilson 
Upvotes   |   0

**Comment by jar398** [comment]
Myzostomida is a genetic outlier and gets put in different places by different studies. I think Annelida could only be seen as nonmonophyletic if you believed both that Myzostomida is outside of it taxonomically (as NCBI says) and that Myzostomida is deep enough inside of it phylogenetically. Both of these claims are pretty weak, so don't call it quits yet.
