### ISSUE TITLE
Species Concept?

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#384]
Which species concept is used in the synthetic tree for which groups?

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   Danielle Wilson 
Upvotes   |   0 
URL   |   [/contact](https://tree.opentreeoflife.org/contact) 
Target node label   |    
Synthetic tree id   |    
Synthetic tree node id   |    
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   None

**Comment by mtholder** [comment]
Hi, The Open Tree project does not do any alpha taxonomy, so I think that it is hard to think of it as having any specific species concept implemented.
We use a taxonomy that is assembled programmatically from other taxonomy inputs (and corrections from users). If you'd like more details on that process see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5515096/

As a result, the species concepts used by many authors get incorporated (via the input taxonomies), and I am confident that their is a lot of internal inconsistency about what species concept is used as you browse across the open tree.

**Comment by opentreeapi** [comment]
Is there a way to add something in the properties area that tells which species concept is used in each study in the Details section?

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   Danielle Wilson 
Upvotes   |   0

**Comment by jar398** [comment]
Not for any feasible level of programming effort.

I doubt there is a simple enumeration of species concepts. The intended design is that if someone cares that much about the details of a species definition, they would trace references, first to the source taxonomy and then to the sources it uses. Unfortunately few of the source taxonomies will tell you which 'taxon concept' (i.e. published description) applies to their use of a name, because a name (even when the authority is known) often gets reused for many difference 'taxon concepts', each perhaps with its own 'species concept', without any indication of the fact - an endemic horror in taxonomy. And then there is the issue that phylogenetic tree curation is not so carefully done that we're always sure a given sample belongs is assigned correctly to an OTT taxon (with its particular 'taxon concept'), even if the names match exactly.

What is your use case, out of curiosity?
