### ISSUE TITLE
Insectivora Wastebasket Taxon

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#385]
I remember reading in different places that Insectivora was a wastebasket taxon and the animals in that section were moved to different categories. Unfortunately I don't remember where I read that from. Is it possible to update the synthetic tree so Insectivora is removed and the families relocated?

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   Danielle Wilson 
Upvotes   |   0 
URL   |   [/contact](https://tree.opentreeoflife.org/contact) 
Target node label   |    
Synthetic tree id   |    
Synthetic tree node id   |    
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   None

**Comment by jar398** [comment]
Agreed. I think this has been discussed before. (Previously reported as #375.) But we can’t include any information without some kind of reference. Any chance you could find us a good modern taxonomic treatment in this area? NCBI claims that its Insectivora has Soricomorpha as a synonym (the name that CoL uses). It’s possible that NCBI has redefined the name to fit some improved hypothesis of monophyly. But it's also possible neither NCBI and CoL is up to date.

Understanding the situation is more work than I can do now, so any help would be welcome.

**Comment by mtholder** [comment]
note that we have the Afrotherian mammals with common names including "shrews" and "moles" in Afrotheria (see https://tree.opentreeoflife.org/taxonomy/browse?id=746703) not in Insectivora (see https://tree.opentreeoflife.org/taxonomy/browse?id=796664 ). So the most egregious cases of Insectivora being a wastebasket are correctly dealt with. There may be some issues remaining, but I'm not aware of them.

There is the question of whether we should call the group "Insectivora" or "Eulipotyphla." I personally wouldn't mind using Eulipotyphla, because it conveys the fact that we aren't using the "old" definition of Insectivora. But NCBI uses Insectivora, so that is was is used in OTT. I don't really mind using "Insectivora".
