### ISSUE TITLE
ott417950 - can't retrieve node_info - 400 Bad Request

### ISSUE THREAD

**Issue by wellcaffeinated** [OpenTreeOfLife/feedback#401]
Hi there
I'm having some trouble digging up this node. I don't think i'm making a bad request... but it says i am ;)

> POST https://api.opentreeoflife.org/v3/tree_of_life/node_info 400 (Bad Request)

request payload:
```
{
  "ott_id": 417950, 
  "include_lineage": true
}
```

**Comment by snacktavish** [comment]
Hi!  
The 'bad request response is a bit confusing. That is happening because a node with that ott_id doesn't exist in the synthetic tree. 
It is in the taxonomy: https://tree.opentreeoflife.org/taxonomy/browse?name=417950,
but in the tree Pan troglodytes is not a monophyletic group (see https://tree.opentreeoflife.org/opentree/argus/ottol@417957/Pan), because this study https://tree.opentreeoflife.org/curator/study/view/pg_1600 breaks up the relationships. We are working on providing better responses when a named named taxon can't be placed in the tree. Right now and API call returns a 400, and the website shows a general message https://tree.opentreeoflife.org/opentree/argus/ottol@417950. Hope that helps!

**Comment by wellcaffeinated** [comment]
Ahhh... interesting
(Physicist/programmer trying to understand phylogenetics here)
Thanks for the quick response
