### ISSUE TITLE
Mixup between Latidae and Latiidae

### ISSUE THREAD

**Issue by jrosindell** [OpenTreeOfLife/feedback#418]
This causes fish such as Hypopterus macropterus to appear among snails. It seems the fish should be in Latidae which is absent from the tree. Instead they are placed in Latiidae which should be populated with molluscs.

**Comment by hyanwong** [comment]
Latiidae is a mollusc family, OTT 645941. It [should only contain a single genus](https://en.wikipedia.org/wiki/Latia), _Latia_ (OTT: 645942), but in the current synth tree this family also contains the fish genera _Hypopterus_ (OTT: 6362442), _Psammoperca_ (OTT: 6362460), and _Lates_ (OTT: 6362444), presumably because these are often classified in Latidae (single 'i')

**Comment by hyanwong** [comment]
Corrected in 12.4. Hurrah! This can be closed
