### ISSUE TITLE
Wolves genus Canis (ott id = 372706) is not in the synthetic tree, but species are.

### ISSUE THREAD

**Issue by LunaSare** [OpenTreeOfLife/feedback#428]

**Comment by snacktavish** [comment]
It looks like Canis it is getting broken up due to the inclusion of _Lycaon pictus_ within Canis in https://tree.opentreeoflife.org/curator/study/view/ot_278/?tab=trees&tree=tree1  and https://tree.opentreeoflife.org/curator/study/view/ot_328/?tab=trees&tree=tree1&conflict=ott 

Because Canis is not monophyletic, it doesn't get mapped onto the synthetic tree.
