### ISSUE TITLE
This fish (the burbot, _Lota lota_) is wrongly placed in the gastropods on the OpenTree

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#441]
The GBIF record shows it is a fish

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Yan Wong](https://github.com/hyanwong) 
Upvotes   |   0 
URL   |   [tree.opentreeoflife.org/opentree/argus/opentree10.4@ott6364776](https://tree.opentreeoflife.org/opentree/argus/opentree10.4@ott6364776) 
Target node label   |   Lota lota 
Synthetic tree id   |   opentree10.4 
Synthetic tree node id   |   ott6364776 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   https://www.gbif.org/species/2415460

**Comment by jar398** [comment]
From GBIF it came, to GBIF it will return.

There are two Lotas and the old GBIF mixed them up. The new GBIF has an overhauled and far superior taxon matcher. Mark's new taxonomy will fix this problem since the problem is fixed in GBIF.

The one you want is OTT 440414 https://tree.opentreeoflife.org/opentree/opentree10.4@ott440414/Lota-lota

**Comment by hyanwong** [comment]
Fixed in 12.3
