### ISSUE TITLE
Choanoflagellates wrongly placed here.

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#45]
They should map to the group marked "Choanomonada" (http://tree.opentreeoflife.org/opentree/argus/ottol@5246832/Choanomonada)
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [hyanwong](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/ottol@202765/Choanoflagellida](http://tree.opentreeoflife.org/opentree/argus/ottol@202765/Choanoflagellida) |
| Target node label | Choanoflagellida |
| Synthetic tree id | otol.draft.22 |
| Synthetic tree node id | 2599305 |
| Source tree id(s) | silva:L29455,ncbi:42893,ncbi:28009,irmng:10270 |
| Open Tree Taxonomy id | 202765 |
| Intended scope | Re: synthetic tree |

**Comment by jar398** [comment]
Great, thanks. This is an interesting one. They both come from SILVA, but
following the Choanoflagellida entry (which has no descendent taxa) leads
via SILVA to a single Genbank record that doesn't link back to the
Choanoflagellida taxon record. It must have linked there at one time, since
NCBI is the source of SILVA names at that level, so NCBI changed its mind.

Just to be sure, is Choanomonada really the new preferred name for this
group? I found it in Paleodb and (as I said) SILVA, but it's unknown to EOL
and wikipedia, both of which cast a pretty wide net, so I'm wondering if
we're sure we want to present the taxon under that name or under the more
popular one.

**Comment by hyanwong** [comment]
I've never seen "Choanomonada" before, and I assume this is a non-standard neologism, although it's not really my field. The standard name is "Choanaflagellida".

**Comment by hyanwong** [comment]
p.s. either way they definitely shouldn't be nested within Ichthyosporea

**Comment by jar398** [comment]
darnit, this one is still in 2.9draft12.

**Comment by hyanwong** [comment]
Do you mean 'choanomonada' (which I reckon should just be killed off)?

**Comment by jar398** [comment]
The problem is that Choanoflagellida is still in Ichthyosporea, which you
said is wrong. I think this is due to a bad match with a different taxon of
the same name in silva. But this is going to require some detective work.

Choanoflagellida(202765)
 order size:37
(202765=ncbi:42893+24 Choanoflagellida) < (5248823=silva:L29455/#6+7
Rhinosporideacae) < (99700=silva:L29455/#5+7 Dermocystida) <
(623671=silva:L29455/#4+49 Ichthyosporea) < (5246131=silva:D14357/#3+5
Holozoa) < (332573=silva:D11377/#2+7 Opisthokonta) <
(304358=silva:D11377/#1+3183 Eukaryota) < (93302=ncbi:131567+3 cellular
organisms) < (805080=silva:0+461 life)
Cristidiscoidia(5653701) subphylum
uncultured Didymoeca sp.(5394933) species
Choanofila(5653700) subphylum
Choanoflagellida sp. MMC-2011a(4038701) species
Choanoflagellatea(4806815) class
Protomonas(5268703) genus
Protomyxa(4038705) genus
unclassified Choanoflagellida(4038697) null
Codosingaceae(5653703) family
...
Synonym: Craspedophyta
Synonym: Choanoflagellata
Synonym: choanoflagellates
Synonym: Choanozoa
Sources:
ncbi:42893,silva:L29455,ncbi:28009,worms:562870,if:90831,gbif:97,irmng:147,irmng:10270
Flags:

**Comment by hyanwong** [comment]
On 13 Oct 2015, at 17:11, Jonathan A Rees notifications@github.com wrote:

> The problem is that Choanoflagellida is still in Ichthyosporea, which you
> said is wrong.

Yes, definitely wrong.

Would it help to get a proper tree of this area? I know some workers in the field, and they are quite helpful. Or does it need sorting at the taxonomy level anyway?

**Comment by jar398** [comment]
In this project, phylogeny trumps taxonomy, so the priority would be to get
a good tree in.

That said, it's also nice to get the taxonomy fixed. It's best if this
happens by coordinating with the major taxonomy providers so that we can
pick up fixes from them, but there is precedent for incorporating
specialized taxonomies into OTT (e.g. Lamiales).

**Comment by hyanwong** [comment]
Just checked on the devtree (https://devtree.opentreeoflife.org/opentree/opentree4.0@1320191/Choanoflagellida), and this is still a problem. Possibly worse, because now there is a species in the (wrongly placed) stub labelled 'Choanoflagellida' - this is certainly an error in placement in one of the taxonomies (?SILVA?). The correct clade (sister to animals) is still badly labelled as 'Choanomonada' - I have had confirmation from a researcher in the field that this is not the preferred name. As before, OToL needs to synonymise Choanomonada as an alternative (less preferred) name for Choanoflagellida, and the clade as a whole should occupy the current position given to Choanomonada (https://devtree.opentreeoflife.org/opentree/opentree4.0@1320042/Choanomonada).

This should be the accepted position in all taxonomies, and has been for a long time, so it is definitely an error somewhere.

**Comment by jar398** [comment]
Agreed. There hasn't been a new taxonomy build since I fixed this problem.
Since we're eager to do a new general release we need some stability and
have pretty much decided to cut bait on changes to 2.9. This will have to
wait until 2.10, I think - which I hope will be soon. I'll bring it up in
our next meeting though.
