### ISSUE TITLE
SUPPRESS In Eukaryota

### ISSUE THREAD

**Issue by hdliv** [OpenTreeOfLife/feedback#5]
Katablepharidophyta (this group has come in as Kathablepharidae from Silva)
DH147-EKD2

**Comment by jar398** [comment]
Should be fixed next build.

**Comment by jar398** [comment]
@hdliv I think this issue is resolved because Katablepharidophyta is synonymized to Kathablepharidae. Here's what I have now for Kathablepharidae:

Kathablepharidae(269577)
 class size:27
    (269577=silva:AB212285/#3+10 Kathablepharidae) < (5246159=silva:L28811/#2+42 Cryptophyceae) < (304358=silva:D11377/#1+3183 Eukaryota) < (93302=ncbi:131567+3 cellular organisms) < (805080=silva:0+461 life)
     Katablepharidaceae environmental samples(5355205) null
     uncultured(5246851) null
     Katablepharidophyta environmental samples(4925560) null
     uncultured Katablepharidaceae(4925559) species
     uncultured katablepharidophyte(4925561) species
     Hatena(561818) genus
     Platychilomonas(4739123) genus
     Leucocryptos(111139) genus
     Roombia(265781) genus
     ...
Synonym: Katablepharidae
Synonym: Katablepharidophyta
Synonym: Katablepharidophycota
Synonym: Katablepharidaceae
Sources: silva:AB212285/#3,ncbi:339960,ncbi:339961,worms:599623,gbif:4918924,irmng:110032
Flags:
