### ISSUE TITLE
Bacterium named "Apis mellifera" with no SILVA information

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#535]
This is presumably some sort of honeybee symbiont, but when I click on the SILVA link on the taxonomy info sidebar, it says "No sequences with an accession number matching "HP459622" were found in our databases."

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [Yan Wong](https://github.com/hyanwong) 
Upvotes   |   0 
URL   |   [https://tree.opentreeoflife.org/opentree/argus/opentree13.4@ott5900566/Apis-mellifera](https://tree.opentreeoflife.org/opentree/argus/opentree13.4@ott5900566/Apis-mellifera) 
Target node label   |   Apis mellifera 
Synthetic tree id   |   opentree13.4 
Synthetic tree node id   |   ott5900566 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   N/A

**Comment by jar398** [comment]
SILVA probably redoes its whole process with each version.  That means that some sequences will be reclassified (because NCBI reclassified them), some will fail their QC process (which is probably improved with each version), and so on.  So this behavior could be because Open Tree is based on a non-current version of SILVA.

One fix might be to move OTT to the latest SILVA.  Another would be to suppress this taxon in a patch, or move it to wherever it belongs.

**Comment by hyanwong** [comment]
Another SILVA misplaced name is _Oncorhynchus mykiss_ (rainbow trout, https://tree.opentreeoflife.org/opentree/argus/ottol@165368), which is also present with a different OTT in the bacteria (https://tree.opentreeoflife.org/opentree/argus/ottol@5256670) - weirdly, this tip doesn't appear in search hits though.

**Comment by hyanwong** [comment]
And another one:https://tree.opentreeoflife.org/opentree/argus/ottol@5901391, which is not a bacterial bumblebee!

**Comment by mtholder** [comment]
this and many more examples will be fixed by https://github.com/OpenTreeOfLife/edOTTs/commit/34d1090debc636663a82f609c1131ba34e871551
