### ISSUE TITLE
Placement of Artiodactyla

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#58]
Artiodactyla is an order within Mammalia rather than a sister group.
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [josh whorley](mailto:joshua.whorley@seattlecolleges.edu) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/otol.draft.22@2983033/Tetrapoda](https://tree.opentreeoflife.org/opentree/otol.draft.22@2983033/Tetrapoda) |
| Target node label | Tetrapoda |
| Synthetic tree id | otol.draft.22 |
| Synthetic tree node id | 2983033 |
| Source tree id(s) | ncbi:32523 |
| Open Tree Taxonomy id | 229562 |
| Intended scope | Re: synthetic tree |

**Comment by mtholder** [comment]
thanks for pointing that out. It is actually just a taxonomic name node that appears there. There are not descendants of that node. All of the artiodactyls are in https://tree.opentreeoflife.org/opentree/otol.draft.22@3066303/Cetartiodactyla
I'll see if I can figure out:
1. why we have Artiodactyla in our taxonomy (OTT), and
2. why the supertree operation is placing that name as sister to mammals.

**Comment by mtholder** [comment]
hi again, the tree shows artiodactyls as one of three groups that are children of the taxon Mammalia. So I don't think that there is any issue with the supertree operation in terms of placement.
I've created an issue in our taxonomy building procedure (https://github.com/OpenTreeOfLife/reference-taxonomy/issues/120#issuecomment-71358800) so that we can start making sure that Artiodactyla in GBIF and IRMNG taxonomies gets associated with the Cetartiodactyla taxon in NCBI.

I've also made an issue suggesting that we prune cases like this during the supertree operation: https://github.com/OpenTreeOfLife/treemachine/issues/153

thanks again, for taking the time to make the comment.

**Comment by jar398** [comment]
NCBI Cetartiodactyla ~= GBIF Artiodactyla in OTT 2.9. That should solve the proximal problem.
(There is a related problem of failure to trim higher taxa that have no non-"hidden" species; that has to be fixed by treemachine, as it is not a taxonomy issue.  This is explained in the comments for [treemachine#153](https://github.com/OpenTreeOfLife/treemachine/issues/153). )
