### ISSUE TITLE
Some examples of groups that are missing in OTT in Eukaryota

### ISSUE THREAD

**Issue by hdliv** [OpenTreeOfLife/feedback#6]
Breviata
Teleonema
Subulatonema
Roombia

**Comment by jar398** [comment]
Thanks for reporting this. This seems to be because when taxonomies are
merged the 'incertae sedis' flags are being combined using OR instead of
AND. I will fix this.

**Comment by jar398** [comment]
No, that's not the right diagnosis, the flags are being handled properly. The problem with Breviatea (which includes Breviata and Subulatomonas) and Telonema, at least, is that SILVA thinks they're incertae sedis. If we include incertae sedis taxa in synthesis and a source tree OTU matches one of them, it's almost certain to lead to problems. This is the policy Stephen and Cody have asked me to implement so you might want to touch base with them if you think it's not right.

Of course if theses taxa are actually disjoint from the other children of Eukaryota there's no problem, so if you want to assert that, I can just move them up to be non-incertae-sedis siblings of the other Eukaryota children. But SILVA does not support that claim. Or if you have a good placement for them based on other evidence I can put them wherever you like.

**Comment by jar398** [comment]
Disposition: awaiting a good placement in OTT for Breviatea; will do nothing until I hear back from you.
Teleonema is known in OTT as Telonema; I will add a synonym.
Roombia is in OTT; I just verified that by searching. Will no nothing.

**Comment by hdliv** [comment]
Breviata is in Amoebozoa

and have the others been handled?

**Comment by jar398** [comment]
In OTT 2.8 (which will be an input to the next synthesis round):
Breviata is a synonym for Breviatea. It is Eukaryota incertae sedis so if
you want it in synthesis in you will have to say what its parent taxon is.
Are you saying the parent taxon is Amoebozoa (i.e. it's a sibling of
Amoebozoa's other children)? (note that's a stronger statement than saying
it's 'in' Amoebozoa, that's why I'm asking for confirmation)

Teleonema is ambiguous (could be synonym for either Pipra or Telonema).
Telonema is incertae sedis so again you will have to nominate a parent
taxon if it's to be seen.

I have no record for Subulatonema in any source taxonomy.

Roombia is in OTT 2.8 without any problem, as a child of Cryptophyceae.

**Comment by jar398** [comment]
I can't figure out what Subulatonema is - tried google and eol - so I'm going to close this issue.  Feel free to re-open or submit a new issue.
