### ISSUE TITLE
Bug reports not correctly associated with node name

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#79]
There seems to be a intermittent problem with the association between node names and bug reports. For example, I reported a minor issue here:

https://tree.opentreeoflife.org/opentree/opentree3.0@979147/Synodontaspis

Which used to appear as a bug report here

https://github.com/OpenTreeOfLife/feedback/issues/78

But now it has disappeared from the Synodontaspis node.I resubmitted but the report seems to have vanished again. There is something odd going on, but I can't pin it down.

**Comment by kcranston** [comment]
Thanks for the bug report. I am not sure what is going on - my comment on this node seems to be placed correctly. The way we refer to nodes is likely to change in the near future, which may help with these sorts of issues. Leaving open while we investigate, though.

**Comment by jimallman** [comment]
According to the issue's metadata, @hyanwong's original comment (#78) was actually entered from this URL (for Oxyprinichthys, rather than Synodontaspis):

https://tree.opentreeoflife.org/opentree/argus/opentree3.0@978886/Oxyprinichthys

The comment does appear at this URL, as expected. I've [searched the feedback issues](https://github.com/OpenTreeOfLife/feedback/search?q=Synodontaspis&type=Issues&utf8=%E2%9C%93) for 'Synodontaspis', and the only instances I see are in this comment and @kcranston's test comment.

**Comment by hyanwong** [comment]
On 20 Aug 2015, at 15:29, Jim Allman notifications@github.com wrote:

> According to the issue's metadata, @hyanwong's original comment (#78) was actually entered from this URL (for Oxyprinichthys, rather than Synodontaspis):

Thanks for checking. I wonder if this is a browser / slow internet issue (I�m in the UK, primarily using Safari on OS X 10.9). Certainly a number of times when I�ve tried to log in on tree.opentreeoflife.org recently the site has timed out completely, and at other times it is remarkably slow from here. I can�t quite see how that might cause the issue though. 

I guess you can probably ignore unless others are having problems too. I�ll keep an eye out and post here if it happens again.

Yan

**Comment by jar398** [comment]
Feel free to re-open the issue if it comes up again.
